# Generated by Django 5.2.1 on 2025-06-04 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitudesProcesos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('tipo_area', models.CharField(max_length=50)),
                ('responsable_seguimiento', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_estimacion', models.DateTimeField()),
                ('estatus', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Completado', 'Completado')], default='Pendiente', max_length=50)),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('retroalimentacion', models.TextField(blank=True)),
                ('aprobado_por', models.CharField(blank=True, max_length=150)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id_proceso', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField()),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitudesprocesos')),
            ],
        ),
    ]
